-d C:\Users\darre\Documents\SquareWavePhaseTest\impl\gwsynthesis\SquareWavePhaseTest.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\darre\Documents\SquareWavePhaseTest\src\SquareWavePhaseTest.cst
-cfg C:\Users\darre\Documents\SquareWavePhaseTest\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
