-d C:\Users\darre\Documents\Senior_Design_Project\Our_Code\TestSquareWave\impl\gwsynthesis\TestSquareWave.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\darre\Documents\Senior_Design_Project\Our_Code\TestSquareWave\src\TestSquareWave.cst
-cfg C:\Users\darre\Documents\Senior_Design_Project\Our_Code\TestSquareWave\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
