-d C:\Users\darre\Documents\ButtonLED\impl\gwsynthesis\ButtonLED.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\darre\Documents\ButtonLED\src\ButtonLED.cst
-cfg C:\Users\darre\Documents\ButtonLED\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
